services:
  xnetmanager:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: xnetmanager_app
    volumes:
      - ./app/xnetmanager/backups:/data/backups
      - ./app/xnetmanager/configurations:/data/configurations
      - ./app/xnetmanager/templates:/data/templates
      - ./.env:/var/www/.env
      - ./src/static:/var/www/static
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: ["/bin/sh", "-c", "python db_init.py && gunicorn --bind 0.0.0.0:8000 --workers 4 manage:app"]
    networks:
      - xnetmanager_bridge
    restart: always

  nginx:
    image: nginx:latest
    container_name: xnetmanager_nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src/static:/var/www/static
    ports:
      - "80:80"
    networks:
      - xnetmanager_bridge
    depends_on:
      - xnetmanager
    restart: always

networks:
  xnetmanager_bridge:
    driver: bridge
