services:
  xnetmanager:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=production
      - BACKUP_DIR=/app/data/backups
      - CONFIG_DIR=/app/data/configurations
      - TEMPLATE_DIR=/app/data/templates
    volumes:
      - ./data/backups:/app/data/backups
      - ./data/configurations:/app/data/configurations
      - ./data/templates:/app/data/templates
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    entrypoint: ["/bin/sh", "-c", "python db_init.py && python manage.py"]
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - xnetmanager
