# Base image
FROM python:3.9-slim

# Install Nginx dan git
RUN apt-get update && \
    apt-get install -y nginx git iputils-ping

# Clone repository from GitHub
RUN git clone https://github.com/deckiokmal/xnetmanager.git /app

# Install Python dependencies
WORKDIR /app
RUN pip install -r requirements.txt

# Configure Nginx
RUN echo "server { \
    listen 80; \
    server_name localhost; \
    location / { \
        proxy_pass http://localhost:5000; \
        proxy_set_header Host \$host; \
        proxy_set_header X-Real-IP \$remote_addr; \
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; \
        proxy_set_header X-Forwarded-Proto \$scheme; \
    } \
}" > /etc/nginx/sites-available/default

# Install ping utils
RUN apt-get install -y iputils-ping

# Expose ports
EXPOSE 80

# Start Nginx and Flask application
CMD service nginx start && flask run --host=0.0.0.0 --port=5000
