"""Customize xmanager_model nullable

Revision ID: 28770caa6d9e
Revises: 486e44d19e30
Create Date: 2024-07-27 02:32:17.746063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28770caa6d9e'
down_revision = '486e44d19e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration_manager', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('device_manager', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('template_manager', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_manager', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('device_manager', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('configuration_manager', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
