"""Initial Migration

Revision ID: 56f0763e31e9
Revises: 
Create Date: 2024-09-03 21:41:11.031403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f0763e31e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('template_manager',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter_name'),
    sa.UniqueConstraint('template_name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('division', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('time_zone', sa.String(length=50), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('secret_token', sa.String(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('backup_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('backup_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_data_user_id'), ['user_id'], unique=False)

    op.create_table('configuration_manager',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_name')
    )
    with op.batch_alter_table('configuration_manager', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_manager_user_id'), ['user_id'], unique=False)

    op.create_table('device_manager',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('ssh', sa.String(length=5), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name'),
    sa.UniqueConstraint('ip_address')
    )
    with op.batch_alter_table('device_manager', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_manager_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('permission_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('git_backup_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('backup_id', sa.String(length=36), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('commit_message', sa.String(length=255), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['backup_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('git_backup_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_git_backup_version_backup_id'), ['backup_id'], unique=False)

    op.create_table('user_backup_share',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('backup_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['backup_data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_backup_share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_backup_share_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_backup_share_user_id'), ['user_id'], unique=False)

    op.create_table('user_configuration_share',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration_manager.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_configuration_share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_configuration_share_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_configuration_share_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_configuration_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_configuration_share_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_configuration_share_configuration_id'))

    op.drop_table('user_configuration_share')
    with op.batch_alter_table('user_backup_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_backup_share_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_backup_share_backup_id'))

    op.drop_table('user_backup_share')
    with op.batch_alter_table('git_backup_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_git_backup_version_backup_id'))

    op.drop_table('git_backup_version')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('device_manager', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_manager_user_id'))

    op.drop_table('device_manager')
    with op.batch_alter_table('configuration_manager', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_manager_user_id'))

    op.drop_table('configuration_manager')
    with op.batch_alter_table('backup_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_data_user_id'))

    op.drop_table('backup_data')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('template_manager')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
