"""Add status column to DeviceManager

Revision ID: 623c7b73856c
Revises: f7c986695273
Create Date: 2024-07-23 22:27:13.743938

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "623c7b73856c"
down_revision = "f7c986695273"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device_manager", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status", sa.String(length=20), nullable=False, server_default="unknown"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("device_manager", "status")


# ### end Alembic commands ###
