"""Add status column to DeviceManager

Revision ID: 64532941e686
Revises: 623c7b73856c
Create Date: 2024-07-24 11:50:15.192223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64532941e686'
down_revision = '623c7b73856c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_manager', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unknown'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_manager', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unknown'"))

    # ### end Alembic commands ###
