"""add tracking user session with force_logout

Revision ID: 92cb6a2dba29
Revises: 9cd6f0161590
Create Date: 2024-09-16 17:32:04.069339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cb6a2dba29'
down_revision = '9cd6f0161590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_logout', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('force_logout')

    # ### end Alembic commands ###
