"""Add device_id foreign key to BackupData model

Revision ID: 9cd6f0161590
Revises: 75d7edca5c2f
Create Date: 2024-09-15 14:31:03.525024

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9cd6f0161590"
down_revision = "75d7edca5c2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backup_data", schema=None) as batch_op:
        batch_op.alter_column(
            "device_id", existing_type=sa.VARCHAR(length=36), nullable=False
        )
        # Tambahkan nama constraint secara eksplisit
        batch_op.create_foreign_key(
            "fk_backup_data_device", "device_manager", ["device_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backup_data", schema=None) as batch_op:
        batch_op.drop_constraint("fk_backup_data_device", type_="foreignkey")
        batch_op.alter_column(
            "device_id", existing_type=sa.VARCHAR(length=36), nullable=True
        )

    # ### end Alembic commands ###
