name: Deploy Flask Application to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

            # Stop and remove the existing container
            docker stop flask_app || true
            docker rm flask_app || true

            # Run the updated container
            docker run -d \
              --name flask_app \
              --restart unless-stopped \
              --env-file /path/to/.env \
              -p 8000:8000 \
              ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

            # Restart nginx to apply any configuration changes
            sudo systemctl restart nginx

      - name: Setup SSL with Certbot
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Install Certbot and renew SSL certificates
            sudo certbot --nginx -d your-domain.com --non-interactive --agree-tos --email your-email@example.com

            # Restart nginx to apply SSL certificates
            sudo systemctl restart nginx
